# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AssessRFC
                                 A QGIS plugin
 Assess Random Forest Classifier (RFC)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-03-19
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Luis Fernando Chimelo Ruiz
        email                : ruiz.ch@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QObject, pyqtSignal
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from qgis.core import *
import numpy as np
import os
import sys
import time
#import RFC
from .random_forest_classifier import importLibs, RandomForestClassifier

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .assess_rfc_dialog import AssessRFCDialog
import os.path

#Get layers QGIS
project = QgsProject.instance()

class AssessRFC:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AssessRFC_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = AssessRFCDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoPatterns')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'Random Forest')
        self.toolbar.setObjectName(u'Random Forest')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Random Forest', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/assess_rfc/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Random Forest'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Assess RFC'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
        return 0

    def run(self):
        """Run method that performs all the real work"""
        
        #TabInput visble
        self.dlg.ui.tabWidget.setCurrentIndex(0)
        #Clear GUIs
        self.dlg.ui.comboBoxClassTrain.clear()
        self.dlg.ui.comboBoxClassVal.clear()
        self.dlg.ui.comboBoxCrit.clear()
        self.dlg.ui.comboBoxTrain.clear()
        self.dlg.ui.comboBoxVal.clear()
        self.dlg.ui.lineEditSegPath.clear()
        self.dlg.ui.lineEditOutClass.clear()
        self.dlg.ui.lineEditAssessFile.clear()
        #SetCheckState
        self.dlg.ui.checkBoxApplyClas.setCheckState(False)
        self.dlg.ui.checkBoxRunTer.setCheckState(False)
        
        #enable
        self.dlg.ui.lineEditOutClass.setEnabled(False)
        self.dlg.ui.buttonOutClass.setEnabled(False)
        #Zero progressaBar
        self.dlg.ui.progressBar.setValue(0)
        #Set criterions Split comboBoxCrit
        self.dlg.ui.comboBoxCrit.addItems(['gini', 'entropy'])
        #Creat Dict with layers names name:layer
        self.dict_layers={'None':None}
        #Insert fields comboBoxs
        self.fields={}
        #Dict with layers names
        dic_layers_qgis =  project.mapLayers()
        for name_layer in dic_layers_qgis.keys():
            #Append name and layer
            self.dict_layers[dic_layers_qgis[name_layer].name()]=dic_layers_qgis[name_layer]
            print (name_layer)
            #assess if is vector
            if dic_layers_qgis[name_layer].type() == 0:
                 #Get field names
                 field_names = [field.name() for field in dic_layers_qgis[name_layer].dataProvider().fields() ]
                 self.fields[dic_layers_qgis[name_layer].name()]=field_names
                 #add name vectors
                 self.dlg.ui.comboBoxTrain.addItem(dic_layers_qgis[name_layer].name())    
                 self.dlg.ui.comboBoxVal.addItem(dic_layers_qgis[name_layer].name())
            else:
                pass

        
        
        #Insert values ComboBoxs                
        if self.dlg.ui.comboBoxTrain.count() == 0:   
            self.dlg.ui.comboBoxTrain.addItem('None')  
            self.dlg.ui.comboBoxClassTrain.addItem('None') 
        else:
            #Get name layer
            names_fields=self.dlg.ui.comboBoxTrain.currentText()           
            #Get and field layer
            self.dlg.ui.comboBoxClassTrain.addItems(self.fields[names_fields])
            
            
        if self.dlg.ui.comboBoxVal.count() == 0:             
            self.dlg.ui.comboBoxVal.addItem('None') 
            self.dlg.ui.comboBoxClassVal.addItem('None')
        else:
            #Get name layer
            names_fields=self.dlg.ui.comboBoxVal.currentText() 
            self.dlg.ui.comboBoxClassVal.addItems(self.fields[names_fields])
            
        #Connect functions
        self.dlg.ui.buttonSegPath.clicked.connect(self.set_segs_path)
        self.dlg.ui.buttonAssessFile.clicked.connect(self.set_assess_file)
        self.dlg.ui.buttonCancel.clicked.connect(self.cancel_GUI)
        self.dlg.ui.buttonRun.clicked.connect(self.run_classification)
        self.dlg.ui.buttonOutClass.clicked.connect(self.set_classification_path)
        
        #Connect functions value changedspinBox
        self.dlg.ui.spinBoxStartEst.valueChanged.connect(self.value_changed_start_est)
        #self.dlg.ui.spinBoxStepSim.valueChanged.connect(self.value_changed_step_sim)
        self.dlg.ui.spinBoxStartDepth.valueChanged.connect(self.value_changed_start_depth)
        
        #Connect functions valueChanged comboBox
        self.dlg.ui.comboBoxTrain.currentIndexChanged.connect(self.value_changed_train)
        self.dlg.ui.comboBoxVal.currentIndexChanged.connect(self.value_changed_val)
        
        #Connect functions CheckBox
        self.dlg.ui.checkBoxApplyClas.stateChanged.connect(self.state_changed_apply_class)
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
        
    def set_classification_path(self):
        #clear lineEdit
        self.dlg.ui.lineEditOutClass.clear()
        #Save shape classification
        out_file = QFileDialog.getSaveFileName(None, self.tr('Save file'), None, " Shapefile (*.shp)")
        #get name and extension file
        name_file= out_file[0].split(os.sep)[-1]
        #Assess extension
        if out_file[-1].split('*')[-1].endswith('.shp)'):
            #insert extension
            if name_file.endswith('.shp'):
                self.dlg.ui.lineEditOutClass.setText(out_file[0])
            else:
                self.dlg.ui.lineEditOutClass.setText(out_file[0]+'.shp')
        else:
            pass
        
    def state_changed_apply_class(self):
        
        state=self.dlg.ui.checkBoxApplyClas.checkState()     
        print ('State apply classification: ',state)
        if state ==2:
            self.dlg.ui.lineEditOutClass.setEnabled(True)
            self.dlg.ui.buttonOutClass.setEnabled(True)
        else: 
            self.dlg.ui.lineEditOutClass.setEnabled(False)
            self.dlg.ui.buttonOutClass.setEnabled(False)            

        
    def value_changed_train(self):
        
        #Clear
        self.dlg.ui.comboBoxClassTrain.clear()      
        #Get name layer
        name_layer=self.dlg.ui.comboBoxTrain.currentText() 
        #Get field names
        #field_names = [field.name() for field in self.dict_layers[name_layer].dataProvider().fields() ]
        #Get and field layer
        self.dlg.ui.comboBoxClassTrain.addItems(self.fields[name_layer])    
        print (self.fields[name_layer])
        return 0
    
    def value_changed_val(self):
        #Clear
        self.dlg.ui.comboBoxClassVal.clear()      
        #Get name layer
        name_layer=self.dlg.ui.comboBoxVal.currentText() 
        #Get field names
        #field_names = [field.name() for field in self.dict_layers[name_layer].dataProvider().fields() ]
        #Get and field layer
        self.dlg.ui.comboBoxClassVal.addItems(self.fields[name_layer])    
        print (self.fields[name_layer])
        return 0        
        
    def value_changed_start_est(self):
        #Set minimum valspinBoxEnd
        self.dlg.ui.spinBoxEndEst.setMinimum(self.dlg.ui.spinBoxStartEst.value())
        #Set maximum valspinBoxStep
        self.dlg.ui.spinBoxStepEst.setMaximum(self.dlg.ui.spinBoxEndEst.value())
        return 0
    
    def value_changed_start_depth(self):
        #Set minimum valspinBoxEndSim
        self.dlg.ui.spinBoxEndDepth.setMinimum(self.dlg.ui.spinBoxStartDepth.value())        
        #Set maximum valspinBoxStep
        self.dlg.ui.spinBoxStepDepth.setMaximum(self.dlg.ui.spinBoxEndDepth.value())        
        return 0
    def set_assess_file(self):
        #Clear
        self.dlg.ui.lineEditAssessFile.clear()
        #Save assess file
        assess_file=QFileDialog.getSaveFileName(None, self.tr('Save file'), None, " Text file (*.txt);;Comma-separated values (*.csv)")
        print(assess_file)
        #print (dir(assess_file[-1]))
        #get name and extension file
        name_file=assess_file[0].split(os.sep)[-1]
        #Assess extension
        if assess_file[0]=='':
            self.dlg.ui.lineEditAssessFile.clear()
            
        elif assess_file[-1].split('*')[-1].endswith('.txt)'):

            #insert extension
            if name_file.endswith('.txt'):
                self.dlg.ui.lineEditAssessFile.setText(assess_file[0])
            else:
                self.dlg.ui.lineEditAssessFile.setText(assess_file[0]+'.txt')
        else:
            if name_file.endswith('.csv'):
                self.dlg.ui.lineEditAssessFile.setText(assess_file[0])
            else:
                self.dlg.ui.lineEditAssessFile.setText(assess_file[0]+'.csv')
        
        
        return 0
    def set_segs_path(self):
        #Open Directory
        self.pathSegs = QFileDialog.getExistingDirectory(None, self.tr('Open a folder'), None, QFileDialog.ShowDirsOnly)  
        #Set lineEditPathSegs
        self.dlg.ui.lineEditSegPath.setText(self.pathSegs)
        return 0
    
    def cancel_GUI(self):
        
        #disconnect       
        self.dlg.ui.buttonAssessFile.clicked.disconnect(self.set_assess_file)
        self.dlg.ui.buttonSegPath.clicked.disconnect(self.set_segs_path)
        self.dlg.ui.buttonCancel.clicked.disconnect(self.cancel_GUI)
        self.dlg.ui.buttonRun.clicked.disconnect(self.run_classification)
        self.dlg.ui.comboBoxTrain.currentIndexChanged.disconnect(self.value_changed_train)
        self.dlg.ui.comboBoxVal.currentIndexChanged.disconnect(self.value_changed_val)
        self.dlg.ui.checkBoxApplyClas.stateChanged.disconnect(self.state_changed_apply_class)
        self.dlg.ui.buttonOutClass.clicked.disconnect(self.set_classification_path)

        self.dlg.close()
        
        return 0
    
      
    def run_classification(self):
        print('Run classification')
        #Assess lineEdit and combobox
        if self.dlg.ui.comboBoxTrain.currentText() == 'None':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Input: Select training samples")
            msg.setWindowTitle("Info")
            msg.exec_() 
            return 0 
        
        elif self.dlg.ui.comboBoxVal.currentText() == 'None':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Input: Select validation samples")
            msg.setWindowTitle("Info")
            msg.exec_() 
            return 0 
        
        elif self.dlg.ui.lineEditSegPath.text() == '':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Input: Undefined segmentation path")
            msg.setWindowTitle("Info")
            msg.exec_() 
            return 0 
        
        elif self.dlg.ui.lineEditOutClass.text() == '':
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Output: Undefined classification path")
            msg.setWindowTitle("Info")
            msg.exec_() 
            return 0 
        
        elif not os.path.exists(self.dlg.ui.lineEditSegPath.text()):
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Input: The path does not exist")
            msg.setWindowTitle("Info")
            msg.exec_() 
            return 0 
        else:
            #Classification path
            classification_path=self.dlg.ui.lineEditOutClass.text()
            #Get name and path layer - Input trainining samples
            name_train = self.dlg.ui.comboBoxTrain.currentText()
            path_train=self.dict_layers[name_train].dataProvider().dataSourceUri().split('|')[0]
            
            #Get name field class - training samples
            field_class_train = self.dlg.ui.comboBoxClassTrain.currentText()
            #Type name field (train)
            fields_train=self.dict_layers[name_train].fields()
            type_field_train = fields_train[fields_train.indexFromName(field_class_train)].typeName()
            print('Type field class (training): '+type_field_train)
            #Get name and path layer - Input validation samples
            name_val=self.dlg.ui.comboBoxVal.currentText()
            path_val=self.dict_layers[name_val].dataProvider().dataSourceUri().split('|')[0]
            #Get name field class - training samples
            field_class_val = self.dlg.ui.comboBoxClassVal.currentText()
            #Type name field (Val)
            fields_val=self.dict_layers[name_val].fields()
            type_field_val = fields_val[fields_val.indexFromName(field_class_val)].typeName()
            print('Type field class (validation): '+type_field_val)
            #data set path
            dataset_path=self.dlg.ui.lineEditSegPath.text() 
            #Values n_estimators
            start_est,end_est,step_est = self.dlg.ui.spinBoxStartEst.value(),\
            self.dlg.ui.spinBoxEndEst.value(),self.dlg.ui.spinBoxStepEst.value()
            #values max_depth
            start_dp,end_dp,step_dp=self.dlg.ui.spinBoxStartDepth.value(),\
            self.dlg.ui.spinBoxEndDepth.value(),self.dlg.ui.spinBoxStepDepth.value()
            #Get criterion
            criterion_split = self.dlg.ui.comboBoxCrit.currentText()
            #Assess exist files
            if not os.path.exists(path_train):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Input: The file does not exist: "+path_train)
                msg.setWindowTitle("Info")
                msg.exec_() 
                return 0 
            if not os.path.exists(path_val):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Input: The file does not exist: "+path_val)
                msg.setWindowTitle("Info")
                msg.exec_() 
                return 0 
            #Get names files segmentations
            segs_names=[f for f in os.listdir(dataset_path)  if f.endswith('.shp')]
            if  segs_names==[]:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Input: The file does not exist (.shp): "+segs_path)
                msg.setWindowTitle("Info")
                msg.exec_() 
                return 0             #Get path assess file
            path_assess_file=self.dlg.ui.lineEditAssessFile.text()
            if  path_assess_file=='':
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Output: Undefined Text path: "+path_assess_file)
                msg.setWindowTitle("Info")
                msg.exec_() 
                return 0   
            #Get plugin path
            plugins_path= QgsApplication.qgisSettingsDirPath()
            #Read file Shell
            path_shell = plugins_path+'python/plugins/assessrfc/run_shell.sh'
            shell=open(path_shell,'w')      
            #Get path python file (RandomForestClassifier)
            rfc_py_path =plugins_path+'python/plugins/assessrfc/rfc.py'
            print ('rfc: ',rfc_py_path)
            print('Shell: ',path_shell)
           
            if self.dlg.ui.checkBoxApplyClas.checkState()==2:
                state_checkBox_Class= 'True'
            else:
                state_checkBox_Class= 'False'
            #arg[1]=path_train
            #arg[2]=segs_path
            #arg[3]=path_val
            #arg[4]=start_est
            #arg[5]=end_est
            #arg[6]=step_est
            #arg[7]=start_dp
            #arg[8]=end_dp
            #arg[9]=step_dp
            #arg[10]=field_class_train
            #arg[11]=field_class_val
            #arg[12]=criterion_split
            
            shell.write('python3 '+rfc_py_path+ ' '+path_train+ ' '+dataset_path+ ' '+\
                        path_val+ ' '+str(start_est)+' '+str(end_est)+' '+str(step_est)+' '+\
                        str(start_dp)+' '+str(end_dp)+' '+str(step_dp)+ ' '+field_class_train+' '+\
                        field_class_val+ ' '+criterion_split+' '+path_assess_file+' '+state_checkBox_Class+' '+classification_path)
            #Close shell
            shell.close()
            #progressbar
            self.dlg.ui.progressBar.setValue(50)
            #Run assess RFC
            if self.dlg.ui.checkBoxRunTer.checkState()==0:
                print('Import libraries')
                #From RandomForestClassifier import lbs
                importLibs()
                print('Run Random Forest Classifier')
                #Run Assess RFC
                RandomForestClassifier(path_train,dataset_path,\
                        path_val,start_est,end_est,step_est,\
                        start_dp,end_dp,step_dp,field_class_train,\
                        field_class_val,criterion_split,path_assess_file,state_checkBox_Class,classification_path)
                print('Finish')
                #progressbar                
                self.dlg.ui.progressBar.setValue(100)
            else:
                if sys.platform == 'linux':
                    #Insert append textEdit
                    print('Run Linux commands')
                   #Exec RFC from shell
                    os.system('chmod u+x '+path_shell+' && '+path_shell)
                    #Insert append textEdit
                    print('Finish')
                    #progressbar                
                    self.dlg.ui.progressBar.setValue(100)
                elif sys.platform=='windows':
                    print('Run Windows caommands')
                    #progressbar                
                    self.dlg.ui.progressBar.setValue(100)
                else:
                    print('Nenhuma plataforma conhecida')
                    #importLibs()
                
   

            
            
